import React, { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { FaEdit, FaTrash, FaFilePdf } from "react-icons/fa";
import { jsPDF } from "jspdf";

function GKViewServices() {
  const navigate = useNavigate();
  const [services, setServices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  // Fetch user-specific services
  const fetchAllServices = async () => {
    const token = localStorage.getItem("authToken");

    if (!token) {
      toast.error("You are not logged in. Please login first.");
      navigate("/login");
      return;
    }

    try {
      const res = await axios.get("http://localhost:5001/api/services/my", {
        headers: { Authorization: `Bearer ${token}` },
      });
      setServices(res.data);
    } catch (err) {
      console.error("Error fetching services:", err);
      if (err.response?.status === 401) {
        toast.error("Unauthorized! Please login again.");
        navigate("/login");
      } else {
        toast.error("Failed to fetch services. Try again later.");
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAllServices();
  }, []);

  // Convert file buffer to base64
  const getFileSrc = (fileUrl) => {
    if (!fileUrl || !fileUrl.data || !fileUrl.contentType) return null;

    try {
      const base64String = btoa(
        new Uint8Array(fileUrl.data.data).reduce(
          (data, byte) => data + String.fromCharCode(byte),
          ""
        )
      );
      return `data:${fileUrl.contentType};base64,${base64String}`;
    } catch (error) {
      console.error("File conversion error:", error);
      return null;
    }
  };

  // Generate PDF for a service
  const handleDownloadPDF = (service) => {
    const doc = new jsPDF();

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(" Service Request Details", 105, 20, { align: "center" });

    // Line
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);

    // Info
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    let y = 40;

    const addRow = (label, value) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(`${value || "N/A"}`, 70, y);
      y += 10;
    };

    addRow("Apartment No", service.aptNo);
    addRow("Service ID", service.serviceId);
    addRow("Contact No", service.contactNo);
    addRow("Contact Email", service.contactEmail);
    addRow("Service Type", service.serviceType);
    addRow("Description", service.description);
    addRow("Status", service.status);
    addRow(
      "Created At",
      service.createdAt ? new Date(service.createdAt).toLocaleString() : "N/A"
    );

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by Livora Service System", 105, 150, { align: "center" });

    doc.save(`service-${service._id}.pdf`);
  };

  // Filtered services
  const filteredServices = services.filter((s) =>
    s.serviceType?.toLowerCase().includes(search.toLowerCase())
  );

  // Find processing service for download button
  const processingService = services.find((s) => s.status === "Processing");

  return (
    <div className="w-full max-w-7xl p-6 mt-0 bg-white rounded-2xl shadow-md font-sans-serif">
      {/* Header */}
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-bold">My Service Requests</h2>

        {/* Search Bar */}
        <div className="flex items-center gap-2 max-w-md w-full ml-20">
          <input
            type="text"
            placeholder="Search by Service Type (e.g., Electrical, Plumbing, Cleaning)"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="border border-gray-300 rounded-lg p-2 w-full focus:ring-2 focus:ring-sky-400"
          />
        </div>

        {/* Download button if service is Processing */}
        {processingService && (
          <button
            onClick={() => handleDownloadPDF(processingService)}
            className="flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600"
          >
            <FaFilePdf size={18} /> Download PDF
          </button>
        )}

        <button
          onClick={() => navigate("/add-service")}
          className="bg-sky-500 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          + New Service
        </button>
      </div>

      {/* Table */}
      {loading ? (
        <p>Loading services...</p>
      ) : filteredServices.length === 0 ? (
        <p className="text-gray-600">No matching service requests found.</p>
      ) : (
        <div className="overflow-x-auto max-h-[70vh]">
          <table className="border border-gray-300 w-full">
            <thead className="sticky top-0 bg-gray-100 z-10">
              <tr>
                <th className="p-3 border text-left">Service ID</th>
                <th className="p-3 border text-left">Contact No</th>
                <th className="p-3 border text-left">Contact Email</th>
                <th className="p-3 border text-left">Service Type</th>
                <th className="p-3 border text-left">Description</th>
                <th className="p-3 border text-left">Attachment</th>
                <th className="p-3 border text-left">Status</th>
                <th className="p-3 border text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredServices.map((s) => {
                const fileSrc = getFileSrc(s.fileUrl);
                return (
                  <tr key={s._id} className="hover:bg-gray-50">
                    <td className="p-3 border">{s.serviceId}</td>
                    <td className="p-3 border">{s.contactNo}</td>
                    <td className="p-3 border">{s.contactEmail}</td>
                    <td className="p-3 border">{s.serviceType}</td>
                    <td className="p-3 border w-5xl">{s.description}</td>
                    <td className="p-3 border">
                      {fileSrc ? (
                        s.fileUrl.contentType.startsWith("image/") ? (
                          <img
                            src={fileSrc}
                            alt="Uploaded"
                            className="w-32 h-20 object-cover rounded-md"
                          />
                        ) : (
                          <a
                            href={fileSrc}
                            target="_blank"
                            rel="noreferrer"
                            className="text-blue-600 underline"
                          >
                            View File
                          </a>
                        )
                      ) : (
                        "No file"
                      )}
                    </td>
                    <td
                      className={`p-3 border ${
                        s.status === "Pending"
                          ? "text-yellow-600"
                          : s.status === "Processing"
                          ? "text-green-600"
                          : "text-green-800"
                      }`}
                    >
                      {s.status || "Pending"}
                    </td>
                    <td className="p-3 border flex flex-col gap-2">
                      <button
                        onClick={() =>
                          s.status === "Pending"
                            ? navigate(`/update-service/${s._id}`)
                            : toast.error("Cannot edit a processing service")
                        }
                        className="flex items-center gap-2 bg-blue-500 text-white px-10 py-1 rounded hover:bg-blue-600"
                      >
                        <FaEdit size={18} /> Edit
                      </button>

                      <button
                        onClick={() =>
                          s.status === "Pending"
                            ? navigate(`/delete-service/${s._id}`)
                            : toast.error("Cannot delete a processing service")
                        }
                        className="flex items-center gap-2 bg-red-500 text-white px-7 py-1 rounded hover:bg-red-600"
                      >
                        <FaTrash size={18} /> Delete
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default GKViewServices;
